server:
  port: 8010
  
spring:
  profiles: dev
  
  application:
    name: eureka-server
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceurl:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost
