server:
    port: 8020
    
spring:
    profiles: dev
  
    application:
        name: microservice-1
    
    message: welcome to microservice 1..
        
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8010/eureka
      
    instance:
        # this is to generate instance id as a unique value
        instance-id: ${spring.application.name}:${random.value}
    
management:
    security:
        enabled: false
