server:
  port: 8030
    
spring:
  profiles: dev
  
  application:
    name: microservice-2
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka
      
  instance:
    # this is to generate instance id as a unique value
    instance-id: ${spring.application.name}:${random.value}
